#!/bin/bash

set -Eeo pipefail

for command in "$@"
do
  echo "--- ${command} ---"
  case "${command}" in
    output-versions)
      pip --version
      python --version
      pipenv --version
      ;;
    check-deps)
        safety check
        ;;
    dep)
        pip install --upgrade pip==23.3
        ./tasks output-versions
        export PATH=~/.local/bin/:$PATH
        pip install --upgrade pip==23.3
        pip install -r requirements.txt
        ./tasks check-deps > audit-output.txt
        ;;
    dojo-dep)
        dojo "./tasks dep"
        ;;
    *)
        echo "Invalid command: '${command}'"
        exit 1
        ;;
  esac
done

set +e