CREATE
        OR REPLACE VIEW mi_sr AS
SELECT col1 AS "RecordType",
         col2 AS "RequestMessageID",
         col3 AS "ConversationID",
         col4 AS "RequestorODS",
         col5 AS "SenderODS",
         col6 AS "RequestorApplicationStatus",
         col7 AS "RequestTime",
         col8 AS "RequestAckTime",
         col9 AS "RequestAckCode",
         col10 AS "RequestAckMessageID",
         col11 AS "RequestAckFailureType",
         col12 AS "RequestAckErrorCode",
         col13 AS "RequestAckErrorDescription",
         col14 AS "RequestAckRetryCount",
         col15 AS "ExtractFailurePoint",
         col16 AS "ExtractFailureTime",
         col17 AS "ExtractFailureMessageID",
         col18 AS "ExtractFailureType",
         col19 AS "ExtractFailureErrorCode",
         col20 AS "ExtractFailureErrorDescription",
         col21 AS "ExtractFailureRetryCount",
         col22 AS "ExtractMessageID",
         col23 AS "ExtractTime",
         col24 AS "LargeMessagingRequired",
         col25 AS "LargeMessageFragmentCount",
         col26 AS "LargeMessageFragmentSentCount",
         col27 AS "LargeMessageFragmentSuccessCount",
         col28 AS "ConversationCloseTime",
         col29 AS "PlaceholdersFileTypeUnsupported",
         col30 AS "PlaceholdersFileDeleted",
         col31 AS "PlaceholdersFileNotFound",
         col32 AS "PlaceholdersFileLocked",
         col33 AS "PlaceholdersUndeterminedReason"
FROM raw_mi
WHERE col1='SR'